center_app/views.py
import flask, flask_login, flask_mail
from werkzeug.utils import secure_filename
from . import forms
from .forms import videos
import center_app
import os
from . import models
from .auth.models import User
from .auth.forms import RegistrationForm
from . import db, login_mgr, mail_mgr
from config import DevConfig
import datetime



main_blueprint=flask.Blueprint('main',__name__)




@main_blueprint.route("/",methods=['GET','POST'])
def index():
    global trial_days_left
    global frm
    global courses
    global start
    global end
    global maximum
    global registered
    global view_course
    registered=None
    frm=User.new_register
    trial_days_left=7
    if flask_login.current_user.is_authenticated:
            trial_days_left=flask_login.current_user.trial_days()

    courses=models.Course.query.all()
    if flask.request.method=="GET":
        start=0
        end=3
    if flask.request.method=="POST" and "contact_us" in flask.request.form:
        start=0
        end=3
        name=flask.request.form.get('name')
        email=flask.request.form.get('email')
        input_msg=flask.request.form.get('input_message')
        flask.flash("Your message has been sent successfully. Royal Project will contact you shortly.")
        msg = flask_mail.Message(subject="Royal Project",
                                     body="{} sent you a message.\n The message is: {}.\nThe return e-mail address is: {}".format(flask.request.form.get('name'),flask.request.form.get('input_message'),flask.request.form.get('email')) ,
                  sender=('ssyelenik@gmail.com'),
                  recipients=['ssyelenik@gmail.com'])
        mail_mgr.send(msg)

    else:
        name="Full Name"
        email="Email Address"
        input_msg="Your Message"

    maximum = len(courses)
    try:
        if end>maximum:
            end=maximum
    except:
        start=0
        end=3
        if end>maximum:
            end=maximum
    try:
        if view_course:
            pass
    except:
        view_course=courses[0]

    if flask.request.method=="POST":
        already_registered=False
        if "login" in flask.request.form:
            user = User.authenticate(
                flask.request.form.get('email'),
                flask.request.form.get('password')
            )
            if user is not None:
                flask.flash("Login successful", 'success')
                return flask.redirect(flask.url_for('main.index'))

            flask.flash("Wrong user mail or password", 'danger')

        if "view_course" in flask.request.form:
            view_course=models.Course.query.filter_by(id=flask.request.form.get('view_course')).first()

            return flask.render_template("/index.html",already_registerd=already_registered,name=name,input_msg=input_msg,email=email,trial_days_left=trial_days_left,courses=courses,frm=frm,view_course=view_course,start=start,end=end)


        if "P" in flask.request.form:
            start-=3
            if start<0:
                start=0
                end=3
            else:
                end=start+3

            if end>maximum:
                end=maximum
        if "0" in flask.request.form:
            start=0
            end=3
            if end>maximum:
                end=maximum
        if "4" in flask.request.form:
            start=3
            end=6
            if start>maximum:
                start=0
                end=3
                if end>maximum:
                    end=maximum
            if end>maximum:
                end=maximum
        if "8" in flask.request.form:
            start=6
            end=9
            if start>maximum:
                start=3
                end=6
                if end>maximum:
                    end=maximum
                if start>maximum:
                    start=0
                    end=3
                    if end>maximum:
                        end=maximum
        if "9" in flask.request.form:
            start=9
            end=12
            if start>maximum:
                start=6
                end=9
                if end>maximum:
                    end=maximum
                if start>maximum:
                    start=3
                    end=6
                    if end>maximum:
                        end=maximum
                    if start>maximum:
                        start=0
                        end=3
                        if end>maximum:
                            end=maximum
        if "12" in flask.request.form:
            start=12
            end=15
            if end>maximum:
                end=maximum
            if start>maximum:
                start=9
                end=12
                if end>maximum:
                    end=maximum
                if start>maximum:
                    start=6
                    end=9
                    if end>maximum:
                        end=maximum
                    if start>maximum:
                        start=3
                        end=6
                        if end>maximum:
                            end=maximum
                        if start>maximum:
                            start=0
                            end=3
                            if end>maximum:
                                end=maximum
        if "N" in flask.request.form:
            if not start+3>maximum:
                start+=3
                if end+3>maximum:
                    end=maximum
                else:
                    end+=3
        if "sign_up" in flask.request.form:
            class_id=flask.request.form['sign_up']
            class_obj=models.Class.query.filter_by(id=class_id).first()
            print(class_obj.type)
            print(flask_login.current_user.membership_status)
            registered=None
            for cl in flask_login.current_user.u_classes:
                if int(cl.id)==int(class_id):
                    registered="already_registered"
                    break

            if not registered=="already_registered":
                flask_login.current_user.u_classes.append(class_obj)
                db.session.commit()
                registered="success"

    return flask.render_template("/index.html",registered=registered,name=name,input_msg=input_msg,email=email,trial_days_left=trial_days_left,courses=courses,frm=frm,view_course=view_course,start=start,end=end)

@main_blueprint.route("/admin",methods=['GET','POST'])
def admin():

    return flask.render_template("/admin/admin.html")

@main_blueprint.route("/manage_user",methods=['GET','POST'])
def manage_user():
    form=forms.AdminUpdateUser()
    user_list=User.query.all()
    u_for_update=user_list[0]
    # form.select_user.choices=select_user_list
    message="none"
    if flask.request.method=="POST":
        message="none"

        if "switch_to_virtual" in flask.request.form:
            all_users=User.query.all()
            for u in all_users:
                u.membership_status="virtual"
                db.session.commit()
                message="updated"

        else:

            user_id=flask.request.form.get('update_user')

            u_for_update=User.query.filter_by(id=user_id).first()

            if "update" in flask.request.form:

                u_for_update.age=flask.request.form.get('age')
                u_for_update.membership_status=flask.request.form['membership_status']
                db.session.commit()
                print(u_for_update.age)
                message="updated"

            if "delete" in flask.request.form:
                if u_for_update.id==flask_login.current_user.id:
                    message="delete_self"
                else:
                    db.session.delete(u_for_update)
                    db.session.commit()
                    message="deleted"

        return flask.render_template("/admin/manage_user.html",form=form,user_list=user_list,u_for_update=u_for_update,message=message)
    return flask.render_template("/admin/manage_user.html",form=form,user_list=user_list,u_for_update=u_for_update,message=message)


@main_blueprint.route("/add_class",methods=['GET','POST'])
def add_class():
    form=forms.AdminAddClass()
    all_courses=models.Course.query.all()
    course_list=[]
    for c in all_courses:
        course_item=(c.id,c.name)
        course_list.append(course_item)
    form.choose_course.choices=course_list
    message="none"
    if flask.request.method=="POST":
        course_id=form.choose_course.data
        name=form.name.data
        start=form.start.data
        end=form.end.data
        days=form.days.data
        hours=form.hours.data
        gender=form.gender.data
        type=form.type.data
        class_obj=models.Class(course_id=course_id,name=name,start=start,end=end,days=days,hours=hours,gender=gender,type=type)
        db.session.add(class_obj)
        db.session.commit()
        message="added"
    return flask.render_template("/admin/add_class.html",form=form,message=message)

@main_blueprint.route("/add_video_to_class",methods=['GET','POST'])
def add_video_to_class():
    form=forms.AdminClassVideo()
    all_classes=models.Class.query.all()
    class_list=[]
    for c in all_classes:
        if c.type=="virtual":
            class_item=(c.id,c.name)
            class_list.append(class_item)
    form.name.choices=class_list
    message="none"
    if flask.request.method=="POST":
        class_id=form.name.data
        sequ_nb=form.sequ_nb.data
        video_obj=models.Video.query.filter_by(class_id=class_id)

        for v in video_obj:
            if sequ_nb==v.sequ_nb:
                override_video_id=v.id
                message="duplicates"
                break
        f=form.video.data
        filename=secure_filename(f.filename)
        basedir=os.path.abspath(os.path.dirname(__file__))
        path_name=os.path.join('static',filename)
        f.save(os.path.join(basedir,'static',filename))
        if message=="duplicates":

center_app/templates/men.html
{% extends 'base_limit.html' %}
        {% block content %}

<div class="divisions-outer">
    <div class="text-logo divisions-title">Men's Division</div>
    <div class="divisions-gallery carousel slide tablet" data-ride="carousel">
        <div  class="divisions-pics carousel-inner" style="background-color:black;">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/static/men1.jpg" alt="First slide">
            </div>
            <div class="carousel-item" style="width:500px;position:relative;">
                <img class="men-pic2 d-block w-100" src="/static/men2.jpg" alt="Second slide">
            </div>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="text-logo schedule-title">Men's Class Schedule</div>
    <div class="schedule-outer tablet">
        <img class="schedule-img d-block w-100" src="/static/schedule.jpg">
    </div>
</div>

        {% endblock content %}

center_app/templates/nav.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>The Royal Project</title>
      <link href="https://fonts.googleapis.com/css2?family=Sigmar+One&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Monoton&family=Sigmar+One&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
        .nav-link{
        font-family: 'Russo One', sans-serif;
        font-size:15px;
        }
        .navbar-brand{
        font-family: 'Russo One', sans-serif;
        font-size:25px;
        }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
        #start_now:hover{
        background-color:#0d47a1!important;
        color:white!important;
        }
        .right{
        padding-top:20px;padding-bottom:20px;text-align:center;
        }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
body {
  margin: 0;
  height: 1000px;
  font-family: 'Open Sans', sans-serif;
}

.top {
  margin: 0;
  position: relative;
  <!--width: 90%;-->
  background-color: #aaa;
  height: 300px;
  opacity: 1;
  text-align: center;
  font-family: 'helvetica';
  font-size: 80px;
  font-weight: 100;
  color: #fff;
}

.title {
  position: absolute;
  top: 10%;
  left: -100px;
}
@import url(https://fonts.googleapis.com/css?family=Open+Sans);


/* The device with borders */
.tablet {
  position: relative;
  width: 600px;
  height: 750px;
  margin: auto;
  border: 16px black solid;
  border-top-width: 60px;
  border-bottom-width: 60px;
  border-radius: 36px;
}

/* The horizontal line on the top of the device */
.tablet:before {
  content: '';
  display: block;
  width: 60px;
  height: 5px;
  position: absolute;
  top: -30px;
  left: 50%;
  transform: translate(-50%, -50%);
  background: white;
  border-radius: 10px;
}

/* The circle on the bottom of the device */
.tablet:after {
  content: '';
  display: block;
  width: 35px;
  height: 35px;
  position: absolute;
  left: 50%;
  bottom: -65px;
  transform: translate(-50%, -50%);
  background: white;
  border-radius: 50%;
}

/* The screen (or content) of the device */
.tablet .content {
  width: 600px;
  height: 635px;
  background: white;
  margin: -1px;
}



.thumb {
    width: 500px;
    height: 400px;
    margin: 70px auto;
    perspective: 1000px;
}

.thumb a {
    display: block;
    width: 100%;
    height: 100%;
    background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)),
		url("/static/shoes2.jpg");
    background-size: 0, cover;
    transform-style: preserve-3d;
    transition: all 0.5s;
}

.thumb:hover a {
    transform: rotateX(80deg);
    transform-origin: bottom;
}
.thumb a:after {
    content: '';
    position: absolute;
    left: 0;
    bottom: 0;
    width: 100%;
    height: 36px;
    background: inherit;
    background-size: cover, cover;
    background-position: bottom;
    transform: rotateX(90deg);
    transform-origin: bottom;
}
.thumb a span {
    color: white;
    text-transform: uppercase;
    position: absolute;
    top: 100%;
    left: 0;
    width: 100%;
    font: bold 12px/36px "Open Sans";
    text-align: center;
    transform: rotateX(-89.99deg);
    transform-origin: top;
    z-index: 1;
}
.thumb a:before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5);
    box-shadow: 0 0 100px 50px rgba(0, 0, 0, 0.5);
    transition: all 0.5s;
    opacity: 0.15;
    transform: rotateX(95deg) translateZ(-80px) scale(0.75);
    transform-origin: bottom;
}

.thumb:hover a:before {
    opacity: 1;
    box-shadow: 0 0 25px 25px rgba(0, 0, 0, 0.5);
    transform: rotateX(0) translateZ(-60px) scale(0.85);
}


#movetxt {
    -webkit-animation: moving 10s infinite;
    animation: moving 10s infinite;
}
@keyframes moving {
    from {transform: translateX(0px);}
    to {transform: translateX(2000px);}
}
.info_area1{
        margin-top:50px;
        margin-right:50px!important;
        }
.info_area1H{
        font-size:3.5rem!important;
        }
.info_area1P{
        font-size:1.5rem!important;
        }

The easiest way to do this is with 2 divs, 1 with the background and 1 with the text:

#reg_pic_o {
  position: relative;
  width: 300px;
  height: 200px;
}
#reg_pic {
  background: #CCC;
  filter: alpha(opacity=60);
  /* IE */
  -moz-opacity: 0.6;
  /* Mozilla */
  opacity: 0.6;
  /* CSS3 */
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
}
#reg_text {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
    </style>
    <!-- Custom styles for this template -->

  <body>
  <div class="wrapper" style="background-size:cover;background-image:url('logo4.png');background-attachment: fixed; background-repeat: no-repeat; width:100%;" >
      <nav class="navbar navbar-expand-md bg-transparent fixed-top" >
        <a class="navbar-brand" href="{{url_for('main.index')}}" style="font-size:2.5rem;"><img style="height:100px;border-radius:50%;" src="/static/logo2.png" > the ROYAL PROJECT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse" style="display:flex;height:80px;" >
          <ul class="navbar-nav mr-auto" >
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('main.index')}}">HOME <span class="sr-only">(current)</span></a>
            </li>
             <li class="nav-item active">
              <a class="nav-link" href="#">ABOUT US <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">VIEW COURSES</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">CONTACT US</a>
            </li>

              </ul>
            <ul class="navbar-nav ml-auto" >
            <li class="nav-item">
              <a class="nav-link right" href="#">HELLO </a>
            </li>
            {% if current_user.role==3 %}
                <li class="nav-item">
              <a class="nav-link right" href="{{url_for('main.admin')}}">VIEW PROFILE </a>
            </li>
               {% endif %}
            <li class="nav-item">
              <a class="nav-link right" href="{{url_for('auth.login')}}">VIEW PROFILE </a>
            </li>
            <li class="nav-item">
              <a class="nav-link right" href="{{url_for('auth.logout')}}">LOGOUT</a>
            </li>
            <li class="nav-item">
             <button data-toggle="modal" data-target="#login" type="button" class="nav-link right highlight" style="border:none;background-color:#d0d6e2;width:200px;" onmouseover="this.style.color='white';this.style.background='#0d47a1';" onmouseout="this.style.color='gray';this.style.background='#d0d6e2';">LOGIN</button>
            </li>
            <li class="nav-item">
              <a href="{{url_for('auth.register')}}" class="nav-link right highlight" style="border:none!important;background-color:#4285F4;width:200px;color:white;" onmouseover="this.style.color='white';this.style.background='#0d47a1';" onmouseout="this.style.color='white';this.style.background='#4285F4';" >REGISTER</a>
            </li>
           </ul>
          <!--<form class="form-inline mt-2 mt-md-0">-->
            <!--<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
            <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
          <!--</form>-->
        </div>
      </nav>

      {% block bod %}
      {% endblock bod%}

center_app/templates/virtual.html
{% extends 'base_limit.html' %}

{% block content %}

<div  class="container" style="position:relative;color:black;width:100%;height:1300px;">




<!--*************************VIEW COURSES**************************-->
<!-- START THE FEATURETTES -->
<div id="view_courses"></div>

<div style="height:125px;"></div>
<!--<hr class="featurette-divider">-->
<h1 style="">Welcome to the Virtual Environment!</h1>
<hr style="margin-left:-320px;">
    <div style="margin-left:-250px;margin-right:-250px;" class="row featurette" >

    <div data-aos="fade-right" data-aos-offset="50"
         data-aos-delay="100"
         data-aos-duration="1000"
         data-aos-easing="ease-in-out"
         data-aos-mirror="true"
         data-aos-once="false"
         data-aos-anchor-placement="top-center" class="col-md-7">

    <div class="container" style="position:relative;">
        <div class="course-list-white"></div>
        <div class="course-list-style">
            <h3 class="featurette-heading" style="color:black;"> <i class="text-muted">Choose a Class:</i></h3>



            <form action="" method="POST">

                {% for i in range(start,end) %}

                <ul class="course_list">

                    <li class="lead" >
                        <h5>Course Name:<i> <strong>{{courses[i].name}}</strong></i>&nbsp<button class="course_button" type="submit" value={{courses[i].id}} name="view_course"><strong>Details</strong></button></h5>
                    </li>
                    <li class="lead" >
                        <p><strong>Course Description: </strong>{{courses[i].description}} </p>
                    </li>
            <!--        <li class="lead">
                        <button class="course_button" type="submit" value={{courses[i].id}} name="view_course"><strong>View Course Details</strong></button>
                    </li>-->

                </ul>

                {% endfor %}



            <nav aria-label="Page navigation example" >
              <ul class="pagination" style="margin-top:-17px;">
                <li class="page-item"><button name="P" class="page-link">Previous</button></li>
                <li {% if end<4 %} style="opacity:.6;" {% endif %} class="page-item"><button name="0" class="page-link"  href="#">1</button></li>
                <li {% if end>3 and end<7 %} style="opacity:.6;" {% endif %} class="page-item"><button name="4" class="page-link"  href="#">2</button></li>
                <li {% if end>6 and end<10 %} style="opacity:.6;" {% endif %} class="page-item"><button name="8" class="page-link" href="#">3</button></li>
                  <li {% if end>9 and end<13 %} style="opacity:.6;" {% endif %} class="page-item"><button name="9" class="page-link" href="#">4</button></li>
                  <li {% if end>12 and end<16 %} style="opacity:.6;" {% endif %} class="page-item"><button name="12" class="page-link" href="#">5</button></li>
                <li class="page-item"><button name="N" class="page-link"  href="#">Next</button></li>
              </ul>
            </nav>

            </form>
</div>
        </div>
    </div>

<!--********************************VIEW AND CHOOSE A CLASS********************************-->
    <div data-aos="fade-left" data-aos-offset="100"
         data-aos-delay="50"
         data-aos-duration="1000"
         data-aos-easing="ease-in-out"
         data-aos-mirror="true"
         data-aos-once="false"
         data-aos-anchor-placement="top-center" class="col-md-5">
        <div class="tablet choose" >
            <div class="tablet_inner" style="margin-top:10px;">
                <form action="" method="POST">
                    <h1 style="color:black;" class="course_details_name">{{view_course.name}}&nbsp </h1>

 {% for class in view_course.c_class %}
                    {% if class.type == "virtual" %}

            <h1 class="course_details_name" style="color:purple;background-color:lightblue;text-align:center;"><i>{{class.name}}&nbsp&nbsp({{class.type}})</i></h1>
            <button class="course_button" type="submit" value={{class.id}} name="watch_class"><strong>Watch Class</strong></button>
<br><br>



{% endif %}
                {% endfor %}



                </form>

            </div>

        </div>
    </div>
</div>


        </div>





{% endblock %}

center_app/templates/watch.html
{% extends 'base_limit.html' %}

{% block content %}

<div  class="container" style="position:relative;color:black;width:100%;height:1300px;">

        <div class="watch-white"></div>
        <div style="position:absolute;top:15px;left:20px;width:950px;height:730px;">



<!--*************************VIEW COURSES**************************-->
<!-- START THE FEATURETTES -->
<div id="view_courses"></div>

<div style="height:125px;"></div>
<!--<hr class="featurette-divider">-->
<h1 style="margin-left:-100px;">Watch the&nbsp<span class="text-muted"><i>{{class_obj.name}}</i></span>&nbsp Videos! <a class="btn btn-primary" style="width:130px;"   href="{{url_for('main.virtual')}}" >Done!</a></h1>

<!--********************************Watch Videos********************************-->
    <div data-aos="fade-left" data-aos-offset="100"
         data-aos-delay="50"
         data-aos-duration="1000"
         data-aos-easing="ease-in-out"
         data-aos-mirror="true"
         data-aos-once="false"
         data-aos-anchor-placement="top-center" class="col-md-5">
        <div class="tablet watch" >
            <div class="tablet_inner" style="margin-top:10px;display:flex;flex-wrap:wrap;">

 {% for video in class_obj.c_video %}

<div style="padding:20px;">
<video style=width="224" height="168" controls>
  <source src="{{video.video_filename}}" type="video/mp4">
</video>
                      <p>Sequence Number: {{video.sequ_nb}}</p>
</div>
{% endfor %}








            </div>

        </div>
    </div>
</div>
</div>







{% endblock %}

center_app/templates/women.html
{% extends 'base_limit.html' %}
        {% block content %}

<div class="divisions-outer">
    <div class="text-logo divisions-title">Women's Division</div>
    <div class="divisions-gallery carousel slide tablet" data-ride="carousel">
        <div  class="divisions-pics carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="/static/women1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/static/women6.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/static/women3.jpg" alt="Third slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/static/women4.jpg" alt="Fourth slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="/static/women5.jpg" alt="Fifth slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="text-logo schedule-title">Women's Class Schedule</div>
    <div class="schedule-outer tablet">
        <img class="schedule-img d-block w-100" src="/static/schedule.jpg">
    </div>
</div>

        {% endblock content %}